site_name: Pypangraph Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: 
    - tutorial1.md
    - tutorial2.md
    - tutorial3.md
    - tutorial4.md
theme:
  name: material
  palette:
    primary: indigo
    accent: deep orange
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences